# include: package:effective_dart/analysis_options.yaml
include: package:lint/analysis_options.yaml
analyzer:
  errors:
    # unused_import: ignore
    # deprecated_member_use: ignore
    missing_return: ignore
  exclude:
    - lib/theme/jam_icons_icons.dart
